import os
from fpdf import FPDF
import tempfile

class MedicalReport(FPDF):
    def header(self):
        # Professional Teal Header
        self.set_fill_color(0, 102, 102) # Teal
        self.rect(0, 0, 210, 20, 'F')
        self.set_font('Arial', 'B', 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, 'MediSight AI Diagnostic Report', 0, 1, 'C')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def section_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(230, 230, 230) # Light Grey
        self.set_text_color(0, 0, 0)
        self.cell(0, 8, f"  {label}", 0, 1, 'L', 1)
        self.ln(4)

def create_pdf(patient_image, predictions, rag_findings):
    pdf = MedicalReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- TOP SECTION: SPLIT LAYOUT ---
    # We use explicit XY coordinates to create a 2-column look
    
    # 1. Patient Image (Left)
    pdf.section_title("1. Patient Scan Analysis")
    
    start_y = pdf.get_y()
    
    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp_img:
        patient_image.save(tmp_img.name)
        # Image at x=10, y=current, width=70mm
        pdf.image(tmp_img.name, x=10, y=start_y, w=70)
    
    # 2. Probability Table (Right side of image)
    # Move cursor to the right
    pdf.set_xy(90, start_y)
    pdf.set_font("Arial", "B", 10)
    pdf.cell(100, 8, "AI Probability Assessment (Zero-Shot)", 0, 1)
    
    pdf.set_font("Arial", "", 10)
    pdf.set_xy(90, pdf.get_y())
    
    # Table Header
    pdf.set_fill_color(240)
    pdf.cell(60, 8, "Condition", 1, 0, 'L', 1)
    pdf.cell(30, 8, "Confidence", 1, 1, 'L', 1)
    
    # Table Rows
    for condition, score in predictions:
        if score > 0.01:
            pdf.set_xy(90, pdf.get_y() + 8) # Move to next row
            pdf.cell(60, 8, str(condition), 1)
            
            # Highlight high risk in red
            if score > 0.5 and "Healthy" not in str(condition):
                pdf.set_text_color(200, 0, 0)
            else:
                pdf.set_text_color(0, 0, 0)
                
            pdf.cell(30, 8, f"{score*100:.1f}%", 1, 0)
            pdf.set_text_color(0, 0, 0)

    # Move cursor below the image area (approx 80mm down)
    pdf.set_y(start_y + 80)
    pdf.ln(5)

    # --- BOTTOM SECTION: RAG IMAGES ---
    pdf.section_title("2. Clinical Evidence (Visually Similar Cases)")
    
    if not rag_findings:
        pdf.cell(0, 10, "No similar cases found in database.", ln=True)
    else:
        # Loop through findings and place them in a grid
        # We allow 3 images max side-by-side
        x_positions = [10, 75, 140] # X coordinates for 3 columns
        y_pos = pdf.get_y()
        
        for i, case in enumerate(rag_findings[:3]): # Limit to top 3
            x = x_positions[i]
            
            # 1. Load the Reference Image
            ref_img_path = os.path.join("data", "reference_images", case['filename'])
            
            if os.path.exists(ref_img_path):
                # Draw Image (Width 60mm)
                pdf.image(ref_img_path, x=x, y=y_pos, w=60, h=60)
            else:
                pdf.rect(x, y_pos, 60, 60) # Placeholder box if image missing
                pdf.text(x+5, y_pos+30, "Image Missing")

            # 2. Add Caption Below Image
            pdf.set_xy(x, y_pos + 62) # Move below image
            pdf.set_font("Arial", "B", 8)
            pdf.multi_cell(60, 4, f"Match #{i+1}", 0, 'C')
            
            pdf.set_xy(x, pdf.get_y())
            pdf.set_font("Arial", "", 7)
            
            # Clean text for PDF
            clean_desc = str(case['text']).encode('latin-1', 'ignore').decode('latin-1')
            pdf.multi_cell(60, 3, clean_desc, 0, 'C')

    # --- DISCLAIMER ---
    pdf.set_y(-30)
    pdf.set_font("Arial", "I", 7)
    pdf.set_text_color(100)
    pdf.multi_cell(0, 4, "DISCLAIMER: Generated by MediSight AI. Investigational use only.", 0, 'C')

    return bytes(pdf.output(dest='S'))
# import os
# from fpdf import FPDF
# import tempfile

# class PDFReport(FPDF):
#     def header(self):
#         # Header with Title and Line
#         self.set_font('Arial', 'B', 15)
#         self.cell(80)
#         self.cell(30, 10, 'MediSight AI Diagnostic Report', 0, 0, 'C')
#         self.ln(20)
#         self.line(10, 25, 200, 25) # Draw a line across the page

#     def footer(self):
#         # Footer with page number
#         self.set_y(-15)
#         self.set_font('Arial', 'I', 8)
#         self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

# def create_pdf(patient_image, predictions, rag_findings):
#     """
#     Generates a PDF report and returns the binary data.
#     """
#     pdf = PDFReport()
#     pdf.add_page()
#     pdf.set_auto_page_break(auto=True, margin=15)

#     # --- 1. PATIENT SCAN SECTION ---
#     pdf.set_font("Arial", "B", 12)
#     pdf.cell(0, 10, "1. Patient Scan Analysis", ln=True)
#     pdf.ln(2)

#     # Save temp image
#     with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp_img:
#         patient_image.save(tmp_img.name)
#         # Force image to be 80mm wide
#         pdf.image(tmp_img.name, x=10, w=80)
    
#     # Move cursor down safely (85mm space for image)
#     pdf.ln(85)

#     # --- 2. ZERO-SHOT PREDICTIONS ---
#     pdf.set_font("Arial", "B", 12)
#     pdf.cell(0, 10, "2. AI Probability Assessment (Zero-Shot)", ln=True)
#     pdf.set_font("Arial", "", 10)
    
#     # Header row
#     pdf.set_fill_color(240, 240, 240)
#     pdf.cell(100, 8, "Condition", 1, 0, 'L', 1)
#     pdf.cell(40, 8, "Confidence", 1, 1, 'L', 1)
    
#     for condition, score in predictions:
#         if score > 0.01:
#             pdf.cell(100, 8, str(condition), 1) # Ensure string
            
#             if score > 0.5 and "Healthy" not in condition:
#                 pdf.set_text_color(200, 0, 0)
#             else:
#                 pdf.set_text_color(0, 0, 0)
            
#             pdf.cell(40, 8, f"{score*100:.1f}%", 1, 1)
#             pdf.set_text_color(0, 0, 0)

#     pdf.ln(10)

#     # --- 3. RAG EVIDENCE ---
#     pdf.set_font("Arial", "B", 12)
#     pdf.cell(0, 10, "3. Clinical Precedent (Similar Historical Cases)", ln=True)
#     pdf.set_font("Arial", "", 10)
    
#     if not rag_findings or "Database is empty" in rag_findings[0]:
#         pdf.set_text_color(100, 100, 100)
#         pdf.cell(0, 10, "No historical matches found.", ln=True)
#     else:
#         for i, case in enumerate(rag_findings):
#             # SAFE TEXT CLEANING
#             # 1. Convert to string
#             # 2. Encode/decode to strip weird characters
#             safe_text = str(case).encode('latin-1', 'ignore').decode('latin-1')
            
#             # Explicitly set width to 190mm (A4 width - margins) to prevent the "0 space" error
#             pdf.multi_cell(190, 8, f"- Match #{i+1}: {safe_text}")

#     # --- 4. DISCLAIMER ---
#     pdf.ln(20)
#     pdf.set_font("Arial", "I", 8)
#     pdf.set_text_color(128, 128, 128)
#     pdf.multi_cell(190, 5, "DISCLAIMER: This report is generated by an AI system (MediSight). It is for investigational use only and does not constitute a medical diagnosis.")

#     # Return binary
#     return bytes(pdf.output(dest='S'))